# Generated by Django 5.1.7 on 2025-04-21 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
    ]
