# Generated by Django 5.1.7 on 2025-04-21 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('place', '0003_rename_text_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
    ]
